### PR TITLE
Improvement/vecn iterator

### PR DESCRIPTION
**Pull request by HectorPeeters**
This pull request changes the for loops in the VecN implementation to iterators.

### CODE REVIEW

**Comment by mtesseracttech** [comment]
How does this compile down versus what used to be there?
The previous stuff used to compile down to SIMD instructions iirc.

You can check it by putting it into the Rust playground and setting it to ASM mode with release settings turned on.

**Comment by HectorPeeters** [comment]
In the following example: 

```rust
fn sum_a(a: &Vec<f32>, b: &Vec<f32>) -> Vec<f32> {
    assert_eq!(a.len(), b.len());
    let mut result = vec![0.0; a.len()];
    for i in 0..a.len() {
        result[i] = a[i] + b[i];
    }
    return result;
}

fn sum_b(a: &Vec<f32>, b: &Vec<f32>) -> Vec<f32> {
    assert_eq!(a.len(), b.len());
    a.iter().zip(b.iter()).map(|(a, b)| a + b).collect()
}
```
Both ```sum_a``` and ```sum_b``` result in identical assembly except for two instructions which end up in a different order. The main idea behind changing this was that it's somewhat easier to read and more compact. 

I do think that all the vector code can be replaced by a single vector type with the new const generics for the size of the vector. It would probably be a good idea to include the num_traits then but that would allow us to have a single vector implementation for both integer and float vectors. This can also be applied to matricies.

**Comment by mtesseracttech** [comment]
I just now noticed that they are taking in full-on Vec<T>'s. Would there be a way to turn this into statically allocated arrays, rather than Vec's? Statically allocated arrays should be much more performant and compile to much more optimized code, as the compiler actually sees them as contiguous data, so it ends up using XMM registers for it, for example.

**Comment by HectorPeeters** [comment]
With the new const generics the following example would work:

```rust
type Vec3 = Vector<f32, 3>;
type IVec3 = Vector<i32, 3>;

struct Vector<T, const S: usize> {
    pub e: [T; S],
}
```

Other operators can then be implemented like this

```rust
impl<T: Copy + Default + Add<Output = T>, const S: usize> Add<Vector<T, S>> for Vector<T, S> {
    type Output = Vector<T, S>;

    fn add(self, other: Vector<T, S>) -> Self::Output {
        let mut e = [T::default(); S];
        for i in 0..S {
            e[i] = self.e[i] + other.e[i];
        }
        Self { e }
    }
}
```

or

```rust
impl<T: Copy> Vector<T, 3> {
    pub fn new(x: T, y: T, z: T) -> Self {
        Self { e: [x, y, z] }
    }
}
```

Implementing all vector types like this would greatly reduce the lines of code but some methods might be a bit less readable.

**Comment by HectorPeeters** [comment]
I implemented a generic vector in `improvement/const-generic-vector` to see if it would be a good replacement. The only disadvantage is that for vec2, vec3, and vec4 you cant access fields using `.x`, `.y`, ... since all data is now stored as arrays.

If this seems like a good replacement I will merge that branch into this one.

**Comment by mtesseracttech** [comment]
Hmmm, that's a tricky one, since the direct member access is quite neat to make functions easier to read/write.

**Comment by HectorPeeters** [comment]
This could be implemented using getter methods but I don't know how that gets compiled. And you can still use `vector.e[0]` or `vector[0]` to access specific elements.

**Comment by HectorPeeters** [comment]
Closing this since this gets fixed in the const generics vector implementation

**Pull request closed without merging**
